---

plugins:
  - jest
  - testing-library
  - jest-dom

env:
  jest: true
  browser: true
  es2020: true

parser: '@babel/eslint-parser'

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:testing-library/react'
  - "plugin:jest-dom/recommended"

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  import/extensions: 0
  import/no-unresolved: 0
  no-param-reassign: 0
