---

env:
  node: true
  browser: true
  es2020: true

parser: '@babel/eslint-parser'

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
